{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf500
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;\f1\fnil\fcharset0 Menlo-Bold;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0\c84314;\cssrgb\c0\c0\c0\c4706;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl360\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 runtime: python27\cb1 \
\cb3 api_version: 1\cb1 \
\cb3 threadsafe: true\cb1 \
\cb3 handlers:\cb1 \
\cb3 - url: /\cb1 \
\cb3   static_files: 
\f1\b build
\f0\b0 /index.html\cb1 \
\cb3   upload: 
\f1\b build
\f0\b0 /index.html\cb1 \
\cb3 - url: /\cb1 \
\cb3   static_dir: 
\f1\b build
\f0\b0 \cb1 \
}